version: 2

references:
  cache_key: &cache_key
    jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: *cache_key
          paths:
            - ~/.gradle
      - run:
          name: Run Lint and Tests
          command: ./gradlew lintDebug ktlintDebugCheck testDebug --no-daemon
      - store_artifacts:
          path: lifecycle/extensions/build/reports
      - store_artifacts:
          path: lifecycle/livedata/build/reports
      - store_artifacts:
          path: lifecycle/reactivestreams/build/reports
      - store_artifacts:
          path: lifecycle/viewmodel/build/reports
      - store_artifacts:
          path: paging/runtime/build/reports
      - store_artifacts:
          path: room/runtime/build/reports
      - store_test_results:
          path: lifecycle/extensions/build/test-results
      - store_test_results:
          path: lifecycle/livedata/build/test-results
      - store_test_results:
          path: lifecycle/reactivestreams/build/test-results
      - store_test_results:
          path: lifecycle/viewmodel/build/test-results
      - store_test_results:
          path: paging/runtime/build/test-results
      - store_test_results:
          path: room/runtime/build/test-results
