version: 2

references:
  cache_key: &cache_key
    jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: *cache_key
          paths:
            - ~/.gradle
      - run:
          name: Run Lint and Tests
          command: ./gradlew lintDebug ktlintDebugCheck testDebug
      - store_artifacts:
          path: aackt-lifecycle-extensions/build/reports
      - store_artifacts:
          path: aackt-lifecycle-livedata/build/reports
      - store_artifacts:
          path: aackt-lifecycle-viewmodel/build/reports
      - store_artifacts:
          path: aackt-lifecycle-reactivestreams/build/reports
      - store_artifacts:
          path: aackt-persistence-room-runtime/build/reports
      - store_artifacts:
          path: aackt-paging-runtime/build/reports
      - store_test_results:
          path: aackt-lifecycle-extensions/build/test-results
      - store_test_results:
          path: aackt-lifecycle-livedata/build/test-results
      - store_test_results:
          path: aackt-lifecycle-viewmodel/build/test-results
      - store_test_results:
          path: aackt-lifecycle-reactivestreams/build/test-results
      - store_test_results:
          path: aackt-persistence-room-runtime/build/test-results
      - store_test_results:
          path: aackt-paging-runtime/build/test-results
